from typing import Final
from .custom_types import Float32

TRADING_DAYS_PER_WEEK: Final = Float32(5)
TRADING_DAYS_PER_MONTH: Final = Float32(TRADING_DAYS_PER_WEEK*4 + 1)
TRADING_DAYS_PER_YEAR: Final = Float32(TRADING_DAYS_PER_MONTH*12 + 4)
TRADING_DAYS_PER_5_YEARS: Final = Float32(TRADING_DAYS_PER_YEAR*5)
ANNUALIZATION_FACTOR: Final = Float32(16)
PERCENTAGE_FACTOR: Final = Float32(100)
ANNUALIZED_PERCENTAGE_FACTOR: Final = Float32(ANNUALIZATION_FACTOR * PERCENTAGE_FACTOR)