DEFAULT_TEMPLATE = "plotly_dark"
COLOR_ADJUSTMENT = 'white'
COLOR_PLOT_UNIQUE = '#fc6400'
BACKGROUND_GRAPH_DARK = 'rgba(17, 17, 17, 1)'
BACKGROUND_GRAPH_WHITE = 'rgba(255, 255, 255, 1)'
FONT_FAMILY = 'QuickSand'
FONT_SIZE = '10px'
FONT_TYPE = 'bold'
BASE_COLORS = ["brown", "red","orange", "yellow", "green", "lime", "blue", "cyan"]
