from typing import Final
TRADING_DAYS_PER_WEEK: Final = 5
TRADING_DAYS_PER_MONTH: Final = 21
TRADING_DAYS_PER_YEAR: Final = 256
TRADING_DAYS_PER_5_YEARS: Final = 1280
ANNUALIZATION_FACTOR: Final = 16
PERCENTAGE_FACTOR: Final = 100
ANNUALIZED_PERCENTAGE_FACTOR: Final = ANNUALIZATION_FACTOR * PERCENTAGE_FACTOR