from typing import Final
from numpy import float32
TRADING_DAYS_PER_WEEK: Final = float32(5)
TRADING_DAYS_PER_MONTH: Final = float32(TRADING_DAYS_PER_WEEK*4 + 1)
TRADING_DAYS_PER_YEAR: Final = float32(TRADING_DAYS_PER_MONTH*12 + 4)
TRADING_DAYS_PER_5_YEARS: Final = float32(TRADING_DAYS_PER_YEAR*5)
ANNUALIZATION_FACTOR: Final = float32(16)
PERCENTAGE_FACTOR: Final = float32(100)
ANNUALIZED_PERCENTAGE_FACTOR: Final = float32(ANNUALIZATION_FACTOR * PERCENTAGE_FACTOR)